# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stui < Formula
  desc ""
  homepage "https://github.com/ernesto27/stui"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ernesto27/stui/releases/download/v0.0.4/stui_Darwin_arm64.tar.gz"
      sha256 "a3dadc0fa4ba49162a036408f719567a2a356acfd97462ec010be6c722a22730"

      def install
        bin.install "stui"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ernesto27/stui/releases/download/v0.0.4/stui_Darwin_x86_64.tar.gz"
      sha256 "bc8d2a5af8513815ced68c527fe61734cb970a213d7b8cb343ff28d6bbce0a56"

      def install
        bin.install "stui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ernesto27/stui/releases/download/v0.0.4/stui_Linux_arm64.tar.gz"
      sha256 "0a9743bdb366b4c465115d402fc12fbaf06253a30b71e493240a2193890b0acd"

      def install
        bin.install "stui"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ernesto27/stui/releases/download/v0.0.4/stui_Linux_x86_64.tar.gz"
      sha256 "c88d14ae35b110930ffb360685531ca7f7959aa782b3a09c599c37989c9dc584"

      def install
        bin.install "stui"
      end
    end
  end
end
